version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    hostname: mariadb
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - /home/glpi/db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  glpi:
    image: diouxx/glpi
    container_name: glpi
    hostname: glpi
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      - TIMEZONE=${TIMEZONE}
      - VERSION_GLPI=${GLPI_VERSION}
    volumes:
      - /home/glpi/http:/var/www/html/glpi
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GLPI_PORT}:80"
    restart: always
